export const LOAD_TENANT = 'LOAD_TENANT'
export const LOAD_MONTH = 'LOAD_MONTH'
export const LOAD_TRANSACTION = 'LOAD_TRANSACTION'
export const CREATE_MONTH = 'CREATE_MONTH'
export const SIGLE_TENANT = 'SIGLE_TENANT'
export const ADD_AMOUNT = 'ADD_AMOUNT'
export const SET_USER = 'SET_USER'
export const USER_LOGOUT = 'USER_LOGOUT'